### ISSUE TITLE
minified version

### ISSUE THREAD

**Issue by willhallonline** [infojunkie/socialcalc#5]
Hi,

Wondering whether it would be worth creating a minified version for inclusion into Drupal. Would make the maintenance of the files far easier and also require far less scripts to be individually loaded. something like socialcalc.min.js (also could then potentially look at hosting that on CDNjs or something like that which could then be pulled in far easier).

**Comment by infojunkie** [comment]
Yes, that would be great. Not sure when I would have the time to make it myself, but I do welcome pull requests.

**Comment by infojunkie** [comment]
Merged! Thanks.
