### ISSUE TITLE
Tagging with version numbers

### ISSUE THREAD

**Issue by willhallonline** [infojunkie/socialcalc#9]
We should probably look at doing version numbers. Possible that we get them to match with the appropriate Drupal version. So 1.x for most of this branch, however, when we look at changing over to using sites/all/libraries in Drupal (which I think would warrant a 2.x release) we would probably need version numbers even more.

**Comment by infojunkie** [comment]
Yes, we should definitely use version numbers, although SocialCalc should remain completely decoupled from Sheetnode. Afaict, there are no Drupal dependencies in this repo, and if there are, it's a bug.

**Comment by willhallonline** [comment]
Yep, no problem with version numbers. I put one onto the package.json file previously. I think that it would be nice to pull into Drupal Status Report.
